---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    driver_config:
      box_url: opentable/win-2012r2-standard-amd64-nocm

suites:
  - name: default
    run_list:

      - recipe[powergui::default]

    attributes:
