---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm
    driver_config:
      box_url: opentable/win-2012r2-standard-amd64-nocm
      vm_hostname: false
    transport:
      name: winrm

suites:
  - name: default
    run_list:

      - recipe[powergui::default]

    attributes:
