---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    driver_config:
      box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      vm_hostname: false
    transport:
      name: winrm

suites:
  - name: default
    run_list:

      - recipe[powergui::default]

    attributes:
